Fixed undefined reference to CThreadEvent::AddListener.
./obj_vstdlib_linux32/release/jobthread.o: in function `ThreadWaitForEvents(int, CThreadEvent* const*, bool, unsigned int)':
/team-comtress-2/public/tier0/threadtools.h:1119: undefined reference to `CThreadEvent::AddListener(std::shared_ptr<std::_V2::condition_variable_any>)'

A better idea is to move ThreadWaitForEvents to threadtools.cpp, but that's more prone to merge conflicts right now.